version: '3.3'

services:
  my-api:
    image: my-api:latest
    entrypoint: ["bash", "-c", "uvicorn main:app --host 0.0.0.0 --port 8888 --workers 2"]
    container_name: my_api
    volumes:
      - ./src:/app/src
    ports:
      - "8895:8888"
    ipc: host
    restart: unless-stopped
